version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: activity-tracking-app
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=activity_tracking
            - DB_USERNAME=activity_user
            - DB_PASSWORD=secure_password
            - CACHE_DRIVER=redis
            - SESSION_DRIVER=redis
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - db
            - redis
        networks:
            - activity-network

    db:
        image: mysql:8.0
        container_name: activity-tracking-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: activity_tracking
            MYSQL_USER: activity_user
            MYSQL_PASSWORD: secure_password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        networks:
            - activity-network

    redis:
        image: redis:7-alpine
        container_name: activity-tracking-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - activity-network

    nginx:
        image: nginx:alpine
        container_name: activity-tracking-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
            - ./docker/ssl:/etc/nginx/ssl
        depends_on:
            - app
        networks:
            - activity-network

volumes:
    db_data:
        driver: local
    redis_data:
        driver: local

networks:
    activity-network:
        driver: bridge
